choco install opera
choco install bitwarden
choco install torguard-client
choco install everything
choco install vscode
choco install steam
choco install epicgameslauncher
choco install telegram
choco install plasso
choco install handbrake
choco install vlc
choco install lightshot
choco install tcpoptimizer
choco install qbittorrent
choco install geforce-experience
choco install microsoft-windows-terminal
choco install python3
choco install 7zip.install
